// packages/scanlines-system/scripts/vendor-surface.mjs
export const VENDOR_DEST = 'src/vendor/scanlines-system'
export const VENDOR_FILES = [
  'src/tokens/persistence.ts',
  'src/tokens/hydrate.ts',
  'src/tokens/boot.ts',
  'src/tokens/log.ts',
  'src/react/provider.tsx',
  'src/tokens/signal-color.ts',
  'src/shell/brand-mark.tsx',
  'src/shell/mark-geometry.ts',
  'src/shell/header.tsx',
  'src/shell/surface-config.ts',
  'src/react/field.tsx',
  'src/react/panel.tsx',
  'src/react/button.tsx',
  'src/react/notice.tsx',
  'src/tokens/reset.css',
  'src/tokens/tokens.css',
  'src/tokens/fonts.css',
  'src/styles/shell.css',
  'src/styles/shell-account.css',
  'src/styles/shell-auth.css',
  'src/styles/shell-admin.css',
  'src/styles/backdrop.css',
  'src/styles/account.css',
  'dist/theme-boot.js',
  'dist/theme-boot.inline.ts',
]
