import type { LogoConcept } from './types'

export const concepts: LogoConcept[] = [
  {
    id: 'prompt-cursor',
    name: 'Prompt Cursor',
    lane: 'terminal-systems-retrofuture',
    prompt: 'A command prompt cursor becomes a precise logo mark for an experimental game studio.',
    tags: ['terminal', 'cursor', 'interface'],
    colorTokens: { background: '#101114', foreground: '#f4f1e8', accent: '#5eead4' },
    fontPairing: { display: 'Space Grotesk', body: 'IBM Plex Mono' },
    geometryPreset: 'monospace-grid-cursor',
    motionPreset: 'blink-step',
    symbolRules: ['Use a block cursor as the primary mass.', 'Keep edges square and aligned to a terminal grid.'],
    wordmarkRules: ['Set the wordmark in a compact technical rhythm.', 'Allow one cursor-shaped interruption near the name.'],
    compactLockupRules: ['Reduce to cursor plus short wordmark.', 'Preserve the cursor silhouette at small sizes.'],
    mutationRanges: {
      symmetry: { min: 0.2, max: 0.8 },
      density: { min: 0.15, max: 0.55 },
      noise: { min: 0, max: 0.2 },
      field: { min: 0.1, max: 0.45 },
    },
  },
  {
    id: 'warp-gate',
    name: 'Warp Gate',
    lane: 'terminal-systems-retrofuture',
    prompt: 'A retro-future gateway built from scanlines, brackets, and spatial UI hardware.',
    tags: ['retrofuture', 'gate', 'scanline'],
    colorTokens: { background: '#08090b', foreground: '#e8f0ff', accent: '#ffb000' },
    fontPairing: { display: 'Eurostile', body: 'Inter' },
    geometryPreset: 'concentric-brackets',
    motionPreset: 'radial-warp',
    symbolRules: ['Build the mark from nested portals.', 'Leave a clear central passage through the symbol.'],
    wordmarkRules: ['Use wide display spacing without negative tracking.', 'Echo bracket cuts in selected letter terminals.'],
    compactLockupRules: ['Use the innermost gate as the favicon mark.', 'Avoid thin scanlines below compact sizes.'],
    mutationRanges: {
      symmetry: { min: 0.65, max: 1 },
      density: { min: 0.25, max: 0.7 },
      noise: { min: 0, max: 0.18 },
      field: { min: 0.3, max: 0.8 },
    },
  },
  {
    id: 'wireframe-map',
    name: 'Wireframe Map',
    lane: 'terminal-systems-retrofuture',
    prompt: 'A navigable wireframe world map rendered as a crisp systems logo.',
    tags: ['wireframe', 'map', 'systems'],
    colorTokens: { background: '#0d1320', foreground: '#edf7f6', accent: '#7dd3fc' },
    fontPairing: { display: 'Sora', body: 'IBM Plex Sans' },
    geometryPreset: 'isometric-wire-grid',
    motionPreset: 'map-pan',
    symbolRules: ['Use connected terrain lines, not filled continents.', 'Favor one strong route line through the grid.'],
    wordmarkRules: ['Keep the wordmark calm and readable beside the busy map.', 'Use one grid-derived notch sparingly.'],
    compactLockupRules: ['Crop to one route node and three grid segments.', 'Increase line weight in compact form.'],
    mutationRanges: {
      symmetry: { min: 0, max: 0.35 },
      density: { min: 0.35, max: 0.85 },
      noise: { min: 0.05, max: 0.3 },
      field: { min: 0.45, max: 0.9 },
    },
  },
  {
    id: 'brutalist-glitch',
    name: 'Brutalist Glitch',
    lane: 'terminal-systems-retrofuture',
    prompt: 'A hard-edged brutalist mark distorted by controlled display corruption.',
    tags: ['brutalist', 'glitch', 'display'],
    colorTokens: { background: '#f2efe6', foreground: '#111111', accent: '#ef4444' },
    fontPairing: { display: 'Archivo Black', body: 'DM Sans' },
    geometryPreset: 'offset-block-stack',
    motionPreset: 'glitch-snap',
    symbolRules: ['Start from heavy rectangular slabs.', 'Offset only a few slices so the silhouette remains legible.'],
    wordmarkRules: ['Use a bold compact wordmark.', 'Introduce one horizontal displacement through the letters.'],
    compactLockupRules: ['Flatten to a two-slab icon.', 'Remove micro-glitches before scaling down.'],
    mutationRanges: {
      symmetry: { min: 0.1, max: 0.55 },
      density: { min: 0.4, max: 0.9 },
      noise: { min: 0.15, max: 0.55 },
      field: { min: 0.15, max: 0.5 },
    },
  },
  {
    id: 'ug-monogram',
    name: 'UG Monogram',
    lane: 'terminal-systems-retrofuture',
    prompt: 'A compact Undef Games monogram formed from engineered U and G letter geometry.',
    tags: ['monogram', 'letterform', 'identity'],
    colorTokens: { background: '#12100e', foreground: '#fff8e7', accent: '#22c55e' },
    fontPairing: { display: 'Neue Haas Grotesk', body: 'Inter' },
    geometryPreset: 'interlocked-letter-grid',
    motionPreset: 'draw-on',
    symbolRules: ['Interlock U and G without hiding either letter.', 'Use one shared stem as the structural anchor.'],
    wordmarkRules: ['Let the monogram carry personality while the wordmark stays neutral.', 'Align cap height to the mark grid.'],
    compactLockupRules: ['Use the monogram alone for square placements.', 'Retain the shared stem and inner counter.'],
    mutationRanges: {
      symmetry: { min: 0.45, max: 0.9 },
      density: { min: 0.25, max: 0.65 },
      noise: { min: 0, max: 0.12 },
      field: { min: 0.1, max: 0.35 },
    },
  },
  {
    id: 'undefined-to-play',
    name: 'Undefined to Play',
    lane: 'play-toolmaking-game-objects',
    prompt: 'An undefined symbol resolves into a play triangle and game-ready identity mark.',
    tags: ['play', 'undefined', 'transition'],
    colorTokens: { background: '#fbfaf5', foreground: '#1f2937', accent: '#2563eb' },
    fontPairing: { display: 'Manrope', body: 'Source Sans 3' },
    geometryPreset: 'question-to-play',
    motionPreset: 'resolve-morph',
    symbolRules: ['Begin with ambiguous punctuation-like geometry.', 'Resolve the negative space into a clear play triangle.'],
    wordmarkRules: ['Use friendly geometric letterforms.', 'Match the play angle in one wordmark detail.'],
    compactLockupRules: ['Keep the play triangle readable first.', 'Drop secondary ambiguity in tiny contexts.'],
    mutationRanges: {
      symmetry: { min: 0.25, max: 0.75 },
      density: { min: 0.2, max: 0.6 },
      noise: { min: 0, max: 0.18 },
      field: { min: 0.2, max: 0.55 },
    },
  },
  {
    id: 'modular-nodes',
    name: 'Modular Nodes',
    lane: 'generative-procedural-simulation',
    prompt: 'A procedural network of modular nodes that suggests tools, systems, and emergence.',
    tags: ['procedural', 'nodes', 'network'],
    colorTokens: { background: '#111827', foreground: '#f9fafb', accent: '#a3e635' },
    fontPairing: { display: 'Azeret Mono', body: 'Inter' },
    geometryPreset: 'node-link-modules',
    motionPreset: 'node-propagation',
    symbolRules: ['Use repeated node modules with varied connection lengths.', 'Keep one dominant path through the network.'],
    wordmarkRules: ['Pair the complex symbol with a low-noise wordmark.', 'Use modular spacing that aligns to node intervals.'],
    compactLockupRules: ['Reduce to three nodes and two links.', 'Preserve the dominant path direction.'],
    mutationRanges: {
      symmetry: { min: 0, max: 0.45 },
      density: { min: 0.35, max: 0.9 },
      noise: { min: 0.05, max: 0.35 },
      field: { min: 0.35, max: 0.85 },
    },
  },
  {
    id: 'tile-anomaly',
    name: 'Tile Anomaly',
    lane: 'generative-procedural-simulation',
    prompt: 'A clean procedural tile field with one intentional anomaly becoming the brand signal.',
    tags: ['tiles', 'anomaly', 'pattern'],
    colorTokens: { background: '#f7f3ea', foreground: '#172026', accent: '#e11d48' },
    fontPairing: { display: 'Space Grotesk', body: 'Inter' },
    geometryPreset: 'grid-with-anomaly',
    motionPreset: 'tile-flip',
    symbolRules: ['Use a regular tile field as the base.', 'Make one tile break rotation, color, or scale rules.'],
    wordmarkRules: ['Keep typography orderly to contrast the anomaly.', 'Use the accent only where the system breaks.'],
    compactLockupRules: ['Show a three-by-three tile set with one anomaly.', 'Avoid more than one accent tile.'],
    mutationRanges: {
      symmetry: { min: 0.35, max: 0.85 },
      density: { min: 0.45, max: 0.95 },
      noise: { min: 0, max: 0.25 },
      field: { min: 0.45, max: 0.9 },
    },
  },
  {
    id: 'emergence-chaos',
    name: 'Emergence Chaos',
    lane: 'generative-procedural-simulation',
    prompt: 'A chaotic particle field organizes into a readable studio symbol.',
    tags: ['emergence', 'particles', 'simulation'],
    colorTokens: { background: '#050505', foreground: '#f5f5f5', accent: '#f59e0b' },
    fontPairing: { display: 'Satoshi', body: 'IBM Plex Sans' },
    geometryPreset: 'attractor-particle-field',
    motionPreset: 'swarm-cohere',
    symbolRules: ['Let particles cluster into a simple core silhouette.', 'Keep stray particles sparse around the edge.'],
    wordmarkRules: ['Use steady typography to stabilize the particle mark.', 'Avoid applying particle noise to every letter.'],
    compactLockupRules: ['Collapse particles into a denser core at small sizes.', 'Limit stray particles to the outer quadrant.'],
    mutationRanges: {
      symmetry: { min: 0, max: 0.4 },
      density: { min: 0.35, max: 1 },
      noise: { min: 0.2, max: 0.8 },
      field: { min: 0.4, max: 1 },
    },
  },
  {
    id: 'system-mutations',
    name: 'System Mutations',
    lane: 'generative-procedural-simulation',
    prompt: 'A base geometric system mutates across controlled variants while staying recognizable.',
    tags: ['mutation', 'variants', 'system'],
    colorTokens: { background: '#0f172a', foreground: '#e2e8f0', accent: '#c084fc' },
    fontPairing: { display: 'Chakra Petch', body: 'Inter' },
    geometryPreset: 'parametric-variant-stack',
    motionPreset: 'parameter-sweep',
    symbolRules: ['Show two or three related mutations of one base form.', 'Keep the base axis visible across variants.'],
    wordmarkRules: ['Use a technical display face with measured spacing.', 'Reference parameter ticks only as small details.'],
    compactLockupRules: ['Use the strongest single mutation for icon-only use.', 'Do not stack variants in tiny lockups.'],
    mutationRanges: {
      symmetry: { min: 0.2, max: 0.75 },
      density: { min: 0.3, max: 0.75 },
      noise: { min: 0.05, max: 0.45 },
      field: { min: 0.25, max: 0.8 },
    },
  },
  {
    id: 'dice-pixel-dialogue',
    name: 'Dice Pixel Dialogue',
    lane: 'play-toolmaking-game-objects',
    prompt: 'Dice pips, pixels, and dialogue bubbles combine into a playful game-making mark.',
    tags: ['dice', 'pixels', 'dialogue'],
    colorTokens: { background: '#fffdf7', foreground: '#202124', accent: '#14b8a6' },
    fontPairing: { display: 'Nunito Sans', body: 'Inter' },
    geometryPreset: 'pixel-dice-bubble',
    motionPreset: 'pip-pop',
    symbolRules: ['Blend a speech bubble with dice pips.', 'Use pixel corners without making the bubble brittle.'],
    wordmarkRules: ['Choose rounded type with clear counters.', 'Echo pips as small separators only when space allows.'],
    compactLockupRules: ['Retain the bubble outline and three pips.', 'Simplify pixel corners on small marks.'],
    mutationRanges: {
      symmetry: { min: 0.25, max: 0.8 },
      density: { min: 0.25, max: 0.7 },
      noise: { min: 0, max: 0.2 },
      field: { min: 0.15, max: 0.55 },
    },
  },
  {
    id: 'party-energy',
    name: 'Party Energy',
    lane: 'play-toolmaking-game-objects',
    prompt: 'A kinetic party-game burst built from tokens, sparks, and social play cues.',
    tags: ['party', 'energy', 'tokens'],
    colorTokens: { background: '#161616', foreground: '#fff7ed', accent: '#fb7185' },
    fontPairing: { display: 'Obviously', body: 'DM Sans' },
    geometryPreset: 'radial-token-burst',
    motionPreset: 'bounce-burst',
    symbolRules: ['Build energy from simple tokens radiating outward.', 'Keep a clear center so the burst does not become confetti.'],
    wordmarkRules: ['Use a warm, sturdy display voice.', 'Let one letter bounce or tilt within controlled limits.'],
    compactLockupRules: ['Use a four-token burst around a central dot.', 'Remove secondary sparks in favicon sizes.'],
    mutationRanges: {
      symmetry: { min: 0.15, max: 0.65 },
      density: { min: 0.3, max: 0.85 },
      noise: { min: 0.05, max: 0.4 },
      field: { min: 0.25, max: 0.75 },
    },
  },
  {
    id: 'pixel-to-vector',
    name: 'Pixel to Vector',
    lane: 'play-toolmaking-game-objects',
    prompt: 'A pixel artifact sharpens into a clean vector mark, bridging retro play and modern tools.',
    tags: ['pixel', 'vector', 'tools'],
    colorTokens: { background: '#f8fafc', foreground: '#0f172a', accent: '#f97316' },
    fontPairing: { display: 'Outfit', body: 'Inter' },
    geometryPreset: 'pixel-vector-hybrid',
    motionPreset: 'snap-to-vector',
    symbolRules: ['Combine stair-stepped pixels with one smooth vector curve.', 'Make the transition direction obvious.'],
    wordmarkRules: ['Use clean geometric type.', 'Reference pixel steps only on a single terminal or dot.'],
    compactLockupRules: ['Use a split pixel-and-curve icon.', 'Increase curve thickness to match pixel weight.'],
    mutationRanges: {
      symmetry: { min: 0.25, max: 0.7 },
      density: { min: 0.2, max: 0.65 },
      noise: { min: 0, max: 0.22 },
      field: { min: 0.2, max: 0.6 },
    },
  },
]
