import type { LogoConcept } from './types'

export const concepts: LogoConcept[] = [
  {
    id: 'define-the-game',
    name: 'Define the Game',
    lane: 'play-toolmaking-game-objects',
    prompt: 'An undefined signal is resolved through play until it becomes a clean game mark.',
    tags: ['undefined', 'play', 'resolution'],
    colorTokens: { background: '#07080b', foreground: '#f6f2e8', accent: '#38f8b7' },
    fontPairing: { display: 'Space Grotesk', body: 'IBM Plex Mono' },
    geometryPreset: 'undefined-resolve-play',
    motionPreset: 'resolve-by-interaction',
    symbolRules: ['Start with unstable fragments.', 'Resolve toward one readable play shape.'],
    wordmarkRules: ['Keep the wordmark engineered and calm.', 'Let the mark carry the transformation.'],
    compactLockupRules: ['Use the resolved play core at small sizes.', 'Avoid extra ambiguity in favicon form.'],
    mutationRanges: {
      symmetry: { min: 0.15, max: 0.82 },
      density: { min: 0.2, max: 0.7 },
      noise: { min: 0.05, max: 0.45 },
      field: { min: 0.2, max: 0.65 },
    },
  },
  {
    id: 'command-console',
    name: 'Command Console',
    lane: 'terminal-systems-retrofuture',
    prompt: 'A game-build console compiles failed commands into an unmistakable studio identity.',
    tags: ['terminal', 'compile', 'system'],
    colorTokens: { background: '#08110f', foreground: '#ecfff7', accent: '#00e676' },
    fontPairing: { display: 'IBM Plex Mono', body: 'Inter' },
    geometryPreset: 'console-build-logo',
    motionPreset: 'type-compile-resolve',
    symbolRules: ['Use prompt, cursor, and compiled output as the mark.', 'Show the transition from error to playable.'],
    wordmarkRules: ['Use command syntax sparingly.', 'Make the wordmark feel like output, not decoration.'],
    compactLockupRules: ['Reduce to prompt and resolved cursor.', 'Keep terminal contrast high.'],
    mutationRanges: {
      symmetry: { min: 0.1, max: 0.55 },
      density: { min: 0.25, max: 0.8 },
      noise: { min: 0, max: 0.24 },
      field: { min: 0.2, max: 0.7 },
    },
  },
  {
    id: 'rule-board',
    name: 'Rule Board',
    lane: 'play-toolmaking-game-objects',
    prompt: 'A small board game system breaks one rule, routes a path, and snaps into the logo.',
    tags: ['board', 'rules', 'tiles'],
    colorTokens: { background: '#111018', foreground: '#fff7ed', accent: '#ff4d8d' },
    fontPairing: { display: 'Manrope', body: 'Inter' },
    geometryPreset: 'board-rule-break-logo',
    motionPreset: 'tile-route-snap',
    symbolRules: ['Use board tiles and one illegal move as the brand signal.', 'Let a route produce the logo shape.'],
    wordmarkRules: ['Keep typography friendly and game-table readable.', 'Echo the route only as a small structural detail.'],
    compactLockupRules: ['Use four board tiles plus the rule-break token.', 'Preserve the diagonal route.'],
    mutationRanges: {
      symmetry: { min: 0.25, max: 0.75 },
      density: { min: 0.35, max: 0.9 },
      noise: { min: 0, max: 0.18 },
      field: { min: 0.35, max: 0.85 },
    },
  },
]
